### ISSUE TITLE
Global Bounties broken

### ISSUE THREAD

**Issue by ZachEnt** [colemclaren/ttt#149]

**Comment by colemclaren** [comment]
Please fix your shit @Velkon #148

**Comment by ZachEnt** [comment]
I believe I found a solution to this issue instructions below.
This is exactly what I did as well as repeated it 3 times on 2 different databases to confirm.
1. Have the latest version of sv_tabs_bounties.lua.
2. Replace the entire table in sv_tabs_bounties. lua L116-L118 with "local id = 0" and start the server.
3. Verify server console says the 12 bounties were refreshed and then stop the server.
4. Return to L116 and revert the changes so L116-L118 is now to what it was from the beginning and start the server.
5. Enjoy cross server bounties.

I will close this issue and crate the pull request once daily refresh happens to verify the bounties are refreshed correctly.

**Comment by ZachEnt** [comment]
Can confirm they are working and reset automatically.
